version: "3.9"

services:
  eureka-server:
    image: eureka
    restart: always
    ports:
      - '8888:8888'
  user-management:
    image: ms1test
    restart: always
    ports:
      - '8081:8081'
    environment:
      SPRING_DATASOURCE: jdbc:h2:mem:testdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8888/eureka/
    depends_on:
      - eureka-server
  api-gateway:
    image: gateway
    restart: always
    ports:
      - '6969:6969'
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8888/eureka/
    depends_on:
      - eureka-server