version: "3.9"

services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
  eureka-server:
    image: eureka
    restart: always
    ports:
      - '8888:8888'
  user-management:
    image: ms1test
    restart: always
    ports:
      - '8081:8081'
    environment:
      SPRING_DATASOURCE: jdbc:h2:mem:testdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8888/eureka/
    depends_on:
      - eureka-server
  gestionClient:
    image: msgestionclient
    restart: always
    ports:
      - '8084:8084'
    environment:
      SPRING_DATASOURCE: jdbc:h2:mem:testdb
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: sa
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8888/eureka/
    depends_on:
      - eureka-server
  gestionProduit:
    image: msgestionproduit
    restart: always
    ports:
      - '8999:8999'
    environment:
      SPRING_DATASOURCE: jdbc:h2:mem:testdb
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: sa
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8888/eureka/
    depends_on:
      - eureka-server
  api-gateway:
    image: gateway
    restart: always
    ports:
      - '6969:6969'
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8888/eureka/
    depends_on:
      - eureka-server
  node-app:
    image: nodejs
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - mongodb
    links:
      - mongodb
volumes:
  mongo-data: